### ISSUE TITLE
Add a truck cargo system to the armory.

### ISSUE THREAD

**Issue by Wesreidau** [WW2-SS13/WW13#101]
Cargo trucks and a supply requisition system needs to be created for both Heer and Red Army factions.

**Comment by Bernhaben** [comment]
Aye! We really need more supplies other than the ones that are currently here. Plus it would make sense if they would only arrive on a certain chance, like 80% of it arriving in-tact and 20% the convoy/cargo truck falls to an enemy ambush along the way and loses the supplies.

**Comment by Wesreidau** [comment]
New German base layout will include a 3y 6x space to park the truck sprite inside the armory.
