### ISSUE TITLE
Broken sandstone walls should produce half-constructed sandstone walls instead of girders.

### ISSUE THREAD

**Issue by Wesreidau** [WW2-SS13/WW13#103]
A climbable, partial cover pile of sandstone rubble that takes the place of girders is desired.

**Comment by chesse20** [comment]
nah theres not enough metal in the enginnering room so you can just move the girders and use them when building defensive forts to save on metal

**Comment by M11gamer** [comment]
Sandstone walls will be changed in all maps to brick or wood so closed.
