### ISSUE TITLE
Add picks to the German combat engineers so they can bypass defensive camping on the assault.

### ISSUE THREAD

**Issue by Wesreidau** [WW2-SS13/WW13#104]
A portable hand-pick that digs through rock walls very slowly needs to be identified or created.

**Comment by Bernhaben** [comment]
I made a pick sprite, there is still no directional sprite for it. It's a German WW2 Pick.

![gpick](https://user-images.githubusercontent.com/9884602/28116422-a34bef54-673b-11e7-8930-16a7f2a895fb.png)
