### ISSUE TITLE
Create a trench network surrounding the Russian blockhouses.

### ISSUE THREAD

**Issue by Wesreidau** [WW2-SS13/WW13#105]
Create a trench-digging system that allows trenches to be made by players or in the map editor.

**Comment by Shephoris** [comment]
Please add the Feature request tag to this issue as well.

**Comment by Eddyskingdom** [comment]
dis seems like a good for me if i can do it

**Comment by Eddyskingdom** [comment]
it be unhandy to have them around ter so no but trenches are now in the game
