### ISSUE TITLE
Bullet damage rebalance.

### ISSUE THREAD

**Issue by Wesreidau** [WW2-SS13/WW13#110]
Bullets appear to be punching clean holes in people. Extra pain damage needs to be inflicted to put knockdown power into the weapons, as presently close quarters fighting is exchanging slugs until someone falls over with a broken leg.

The odds of hitting hands, feet and to a lesser extent the head need to be reduced until the meta-game is to shoot for the chest.

**Comment by Bernhaben** [comment]
Yeah, the torso is the largest part of a body that someone can hit with relative ease. A moving limb on the other hand is not... They could however add an accuracy system, per se if you're a sniper, you have a set of skills that would give you a few accuracy bonuses when aiming for limbs while in zoom mode. Or if you're a standard soldier, you get some kind of perks. Similar to how you select perks from CoD.

**Comment by Wesreidau** [comment]
Overall reducing the brute damage caused by bullets and replacing much of it with halloss pain will reduce our incidence of internal organ injury and severed limbs, while dropping people from pain and killing them with bloodloss instead. Bleeding wounds can be readily treated in the field by friends and reduces the field medic's workload to something feasible. Last I checked blood loss is regenerated by the metabolism system, so all the food around the map gets an additional use.

Currently our game is very bloody and one-bullet kills. While appearing realistic, it isn't lending itself to good roleplay because people keep yakkity-saxing with bullets in the chest to get more kills until they die, unless they're inclined to roleplay, then they fall back and die quietly of internal bleeding on the operating table.
