### ISSUE TITLE
Run Speed Could Be Tweaked For Gameplay Balance

### ISSUE THREAD

**Issue by spacebear27** [WW2-SS13/WW13#112]
The speed in which men carrying heavy rifles run, is way too high. If the base run speed isn't going to be changed, then speed reductions should apply based on the weight and size of the weapon you're carrying.

**Comment by Super3222** [comment]
Eh. I get why classes like heavy should get reduction, but I like the soldats speed.

**Comment by Wesreidau** [comment]
Aurora has a system where moving in run mode deals a small amount of oxy damage per tile. This could easily introduce stamina and cut down on the yakkety-sax, although the walking speed would need to be increased somewhat to compensate.

**Comment by Shephoris** [comment]
+1 @Wesreidau 's suggestion, sounds like the best method.

**Comment by MrJJJ2** [comment]
Well its easy to give a say, CN-42 vest or uniform a slowdown, although a weapon slowdown...since most weapons here aren't wielded this might be tricky, but should be possible.

Also we really shouldn't grab a feature from a system that is about Heavy RP while we aren't Heavy RP but meh.

**Comment by Shephoris** [comment]
Astrid said they thought it might be to do with the SWAT shoes (as they're a death squad item)  I checked the move speed for them and it's 10.  This is why people are running so fast.  I still think that the stamina thing should be in place, but I also think the swat shoes need a serious Nerf to stop the whole running around in circles / forwards and backwards combat.
