### ISSUE TITLE
Current filestructure breaks the git module

### ISSUE THREAD

**Issue by martinlyra** [WW2-SS13/WW13#116]
See title. Module in question is `getrev.dm` in `/code/datums/helper_datums`

Effects:
* We cannot get the current revision or any information about which version the server is running - whether it is up-to-date with our public repo or not.
* Future bug reports may be skewed since we have already e.g. fixed it, but is still present in live version and thus get reported.

Suggested solutions:
1. Move all sub-dirs in `Interstation-Two-WW2/` one folder down, to the root folder. (Preferred)
2. Change the directory so it searches for the .git info one folder down. (Quickest low-effort)

**Comment by tylerh95** [comment]
I think we really should be one dir down.

**Comment by martinlyra** [comment]
As in going with solution 1?

**Comment by Supermichael777** [comment]
the current structure is less of a hassle for testing(dme needs to be in a folder with the same name) but yeah.
