### ISSUE TITLE
Kar98k and Mosin Improvements

### ISSUE THREAD

**Issue by Wesreidau** [WW2-SS13/WW13#132]
First: Both bolt action rifles need a cycling delay to prevent hot key or macro rifle spamming. The delay should be placed on the close bolt action (these are both cock-on-close designs).

Second: The Kar98k does not close its bolt on an empty magazine; the magazine follower interferes with the bolt face as a signal to reload. Adjust the Kar98k to not close its bolt when empty.

**Comment by chesse20** [comment]
1. no the macro to clear bolts is good
2. idk how bolt action rifles work

**Comment by tylerh95** [comment]
Cycling delay was added. We will be doing an overhaul of the weapon base to add more realism, however I'm going to wait on the Kar90k bolt thing until then.
