### ISSUE TITLE
Bolt Actions Need Cycling Delay

### ISSUE THREAD

**Issue by Wesreidau** [WW2-SS13/WW13#14]
Currently with hotkeys a player can very quickly cycle the bolt action rifles. This needs to be addressed with a "not ready to fire again" delay after closing the bolt.

It is worth noting the Mosin Nagant has a reputation of poor cycling compared to the Mauser. If a distinction between these two rifles is desired, the Mosin could have a slightly longer firing delay.

**Comment by tylerh95** [comment]
Added
