### ISSUE TITLE
Allow Splints To Be Placed On Any Limb

### ISSUE THREAD

**Issue by Steelpoint** [WW2-SS13/WW13#144]
One of the biggest issues faced by Medics are people suffering from fractured limbs, right now splints really only work on arms and legs, not feet, heads, etc.

Being able to apply splints to any limb would go a long way in making aiming for feet/hands less powerful and help medics in stabilizing people without resorting to lengthy and frustrating surgery.

**Comment by MrJJJ2** [comment]
Agreed, i find it really troublesome that no matter what, if my arm gets shot i can just get a splint, some medicine to help me and still be able to fight and hold items, my hand tho? can't be splinted, and splinting the arm does nothing to help it, so if both of your hands get shot, you are fucked, forever, the only way out is to bite the enemy throat out, somehow.
