### ISSUE TITLE
Something to help with Night time battles

### ISSUE THREAD

**Issue by Bernhaben** [WW2-SS13/WW13#148]
I looked up WW2 Floodlights, and I came up with this:
https://i.ebayimg.com/thumbs/images/g/fygAAOSwDrNZUScP/s-l225.jpg

Here's my horrible attempt to remake it:
![tilleytrolley](https://user-images.githubusercontent.com/9884602/28221971-063125ea-68f8-11e7-9576-7717dca1989c.png)
 On
![tilleytrolleyoff](https://user-images.githubusercontent.com/9884602/28221981-0cae9ce0-68f8-11e7-9dc1-7d41582933b7.png)
 Off

[Floodlight.zip](https://github.com/kachnov/WW13/files/1149136/Floodlight.zip)

The .zip incase anyone wants to tinker with it.

**Comment by printer16** [comment]
Maybe a street lamp?

**Comment by spacebear27** [comment]
It makes more sense to have spotlights, especially in both factions bases.
