### ISSUE TITLE
Add Purely Focused regulation forces for both sides (MPs)

### ISSUE THREAD

**Issue by subdon** [WW2-SS13/WW13#151]
But subdon we have the SS and the Guards...
the Waffen SS fuck off post train departure, yes of course they will take care of medbay thief before train, but afterwards they do their special missions and oftenly are never heard again.
The guards on the other hand, are not even fucking close to MPs, they are just infantry operating a maxim, not guards, they dont have batons, cuffs or anything to make you believe they are guards, just cannon operators.

Slots:
-Feldgendarmerie (German) 2/2
-Political Commisars (Russian) 2/2
Spawn with batons armors and Smgs along with cuffs and fancy hats

**Comment by x0mek** [comment]
Sweet. Always wanted to shoot a deserter/coward as he flees the battlefield, or make a prisoner go out on mineclearing duty.

**Comment by ShinHKPDes** [comment]
Military Police roles for germans and russians were added months ago, closing this.
