### ISSUE TITLE
Neutral Civilians

### ISSUE THREAD

**Issue by x0mek** [WW2-SS13/WW13#152]
These are not necessarily partisans for the Russians per say, these would ideally be whitelisted(?) roles that would live in the towns and among the buildings of the battlefields. Depending on RP, they could side with the Wehrmacht or the Red Army, (or neither) giving out military aid and information. It also provides a more interesting target for the SS to shakedown and gas.

Thematically the only people I could think of that did this would be the Poles, who frequently fought with or against both sides during WWII: https://in.rbth.com/arts/2015/05/14/the_home_army_polish_guerrillas_against_the_red_army_43111

**Comment by tylerh95** [comment]
Neutral citizens were added in with partisans.
