### ISSUE TITLE
Reinforcement Buffing

### ISSUE THREAD

**Issue by subdon** [WW2-SS13/WW13#153]
Allow ONE randomly decided specializated soldier to join along with them PER wave allowing a longer lasting conflict

**Comment by Bernhaben** [comment]
Inb4 squads only spawn with 1 man, and each spawn is a Special Snowflake.

**Comment by chesse20** [comment]
theres currently no reason to have enginners late spawn because theres only enough resources in the enginnering room for one enginner (22 or 30 metal, 30 wood, useless glass, 10? plasteel)
