### ISSUE TITLE
contested area for victory conditions needs to be fixed

### ISSUE THREAD

**Issue by kachnov** [WW2-SS13/WW13#157]
title. 

germans can occupy the areas immediately outside the bunker and still win. It should just be the bunker building, and the underground area.

soviet victory conditions are fine, at least until soviets start winning once in a while

¯\_(ツ)_/¯

**Comment by Wesreidau** [comment]
Here's my position on this.

I need the ability to clearly paint what areas need to be held as a minor territory objective, and a major territory objective. So if I want capturing the town to be the minor victory condition for Germans, there needs to be some zones I can put down for that, including any subsets like houses.

Right now I don't know what areas are used for weighing the victory conditions.

**Comment by subdon** [comment]
Minor: Pond Plaza or Gun factory (place a USSR flag or a statue to make symbolize importance)
Major: Bunker Commander Quarters
