### ISSUE TITLE
Replace One SS Soldat With One SS Medic

### ISSUE THREAD

**Issue by Steelpoint** [WW2-SS13/WW13#162]
The new change to the German medical storage (doors) have been really positive but it has left the SS in a precarious state, because the SS operate in a semi-independent state they lack quicker access to a proper medic and guaze is only good for surface bleeding.

My suggestion is to remove one SS Soldat role and replace it with a dedicated SS medic, the medic should get a small medical locker that has all the standard medical equipment, including a surgical toolset.

**Comment by subdon** [comment]
+1
Maybe a special snowflake medic will encourage people play medic often.
Only request is that waffen SS gets a SEPARATE medical supplies from medbay

**Comment by Super3222** [comment]
I like this idea. Albeit it'll open up a third medic role, it is still a good idea.
