### ISSUE TITLE
Remove Night Map

### ISSUE THREAD

**Issue by Difrit** [WW2-SS13/WW13#166]
I've yet to talk to a player who feels the night map adds anything good that the day map doesn't have. All it encourages is cheesing the game systems and avoiding any meaningful contact with either your own side or the enemy, while you lurk in darkness and just ping grenades at folk. It's no fun for anyone involved.

Please remove.

**Comment by Super3222** [comment]
I played a night map round. It's awful, especially when you try to look down sights. It's one of those ideas that sound great down on paper, but once you implement it gameplay goes south. It's basically a hardmode map, and a very unfun one at that.

**Comment by chesse20** [comment]
the night map is bad and also i spawned in with 100% daylight vision during it once so sometimes wrong with the night map anyways

**Comment by Steelpoint** [comment]
Night Map might be ok if you still had some limited visibility at all times, akin to standing on the edge of a flare source and being barely visible. 

But right now its just a shit show, no visibility removes any semblance of a frontline and has the entire server stumbling in the dark.

Its unfun and tedious.

**Comment by Muncher2112** [comment]
These values where just upped 1/10th across the board, with early morning being fixed as well.  Try it out for a few days and see how if this is still an issue.
