### ISSUE TITLE
Spawned as German Enginner during nightmap, had complete daytime vision

### ISSUE THREAD

**Issue by chesse20** [WW2-SS13/WW13#167]
i was building a fort the whole round but then someone walked up to my fort and asked why i didnt have any flares. turns out i was able to see 100% normally as it was daylight. not sure if enginners spawn with nightvision or it was just an odd glitch. my byond was and still is up to date so i dont know how it happened

**Comment by x0mek** [comment]
This happened to me one time spawning as a soldat. I think it had something to do with using remove darkness as a ghost and then respawning right after.

**Comment by Harcourt1** [comment]
Someone try observing right when round starts. Toggling darkness in ghost menu. Then pressing re-spawn and joining as whatever.
