### ISSUE TITLE
Full Platoon Reorganization, Soviet and German

### ISSUE THREAD

**Issue by Wesreidau** [WW2-SS13/WW13#171]
Red Army organization reference.
http://www.avalanchepress.com/BehindCounters3.php

I lack a Russian to Latin alphabet source. * denotes a translation request.

Heer organization reference.
http://www.avalanchepress.com/BehindCounters.php

Shitty German title reference.
https://s-media-cache-ak0.pinimg.com/736x/06/7b/12/067b1299cb066a2c128f89601ce8a50f--north-africa-scale-model.jpg

Accommodations for gameplay and balance are denoted by ~, translation requests by *.

Therefore.

Red Army Platoon
1-2x Company Physician*~ ( Should only be one and possibly imaginary. Two for gameplay)
Cap or Helmet with Red Cross, unarmed.

1x Platoon Commander* (a lieutenant issuing orders)
Officer's Hat, Nagant M1895 ( 7-shot 7.62x25mm revolver, needs to be made) or pistol in 7.62x25 (the Tokarev, likewise)

1x Platoon Leader* (a senior sergeant enacting orders)
Helmet, SVT-40 or PPSh-41

2x Sniper / Messenger*
Cap, Scoped Mosin-Nagant M1891 (Older, longer version)

3 Squads* ~ (from 4)

3x Squad Leader* (sergeant following orders)
Helmet, SVT-40 or PPSh-41

Per squad,
2x Submachine Gunners*
Helmet, PPSh-41
5x Riflemen*
Cap, Mosin-Nagant M1891/30 (A shorter version)
1x Machine Gunner*
Helmet, DP-28 (needs to be called the DP-28, by the way),
1x Sanitar*~ (No medics on the squad level IRL)
Cap or Helmet with Red Cross, Nagant M1895 ~ (instead of a rifle, to encourage non-combat)

Heer Platoon (Zug)

1-2x Kompaniearzt (Should only be one and possibly imaginary. Two for gameplay)
Cap or Helmet with Red Cross, unarmed.

1x Zugfuhrer (Leutnant, issues orders)
Officer's Cap, Luger

1x Unteroffizier (a senior sergeant enacting orders)
Helmet, MP-40

2x Scharfschütze
Cap, Scoped Gewehr 98 (Older, longer version)

3 Gruppe

3x Gruppenfuhrer* (sergeant following orders)
Helmet, MP-40

Per Gruppe,
1x Gefreiter (assistant squad leader)
Helmet, MP-40
5x Schütze
Helmet, Karabiner 98k (A shorter version)
2x MG-Schütze
Helmet, MG-34
1x Sanitäter ~ (combat medics not attached to squads)
Cap or Helmet with Red Cross, Luger ~ (instead of a rifle, to encourage non-combat)

**Comment by Wesreidau** [comment]
Amend to this any specialists we want like scouts, pioneers, the quartermaster, nurses, cooks...

**Comment by Soundwavesghost** [comment]
Finally someone found this! I knew it existed but I couldn't find it! +1

**Comment by Eddyskingdom** [comment]
it's already done
