### ISSUE TITLE
Movement speed and gun combat tweaks. [Major gameplay enhancement]

### ISSUE THREAD

**Issue by Shephoris** [WW2-SS13/WW13#178]
Reading through issue #112 and seeing this comment, made me think about the games combat mechanics...
> Wesreidau
Aurora has a system where moving in run mode deals a  small amount of oxy damage per tile. This could easily introduce stamina  and cut down on the yakkety-sax, although the walking speed would need  to be increased somewhat to compensate.
--

Along with the "Scope not zooming out when moving" issue that was posted, gave me an idea how to solve my biggest issue of very little RP, comms and squad work, so here goes.

Basically if you take what Wesraidu is saying, and add stamina when someone is running. Making is so that stamina runs out after 30 tiles (the length of the parade ground outside Russian base). This would prevent the dancing in circles combat we so frequently see that is unrealistic, immersion breaking, and promotes rambo'ing.  Walk should be changed to "Jog" which should be around the same speed someone moves without shoes on, perhaps even a slight bit slower, that would not use stamina.

Then implement a forced "Walk speed" for when someone is using Iron sights, so that advances on enemy position are plausible.  With the new fix coming in that disables Irons when you move, it puts people under direct enemy fire, without being able to focus into the distance.

Keep Sniper scopes and Binoculars only able to be used when stood still to prevent power gaming, and we have a winning combination that should slow down combat slightly, allowing for more communication, RP, and generally less "Rush B" rounds. 

Now couple these things with a 5 minute Respawn timer as suggested in #158 , and the game will be more about working as an army, and not about who is better at being a rambo dancer.

**Comment by Schwaglord** [comment]
+1 but it's not l-like i like you or anything

**Comment by bardofrage** [comment]
This looks cool, and making your combat more military styled combat rather than generic ss13 combat would work well with your theme, as well as further distinguishing yourself from other PVP heavy server options, combat should be slower and more tactical, would +1 for sure, If i was on the staff team.

**Comment by chesse20** [comment]
-1 i like the rambo combat

**Comment by UnarmedBastard** [comment]
Okay for the scope thing, not okay for stamina. I like the dynamic playstyle we have now.

**Comment by Shephoris** [comment]
> Okay for the scope thing, not okay for stamina. I like the dynamic playstyle we have now.

Currently the game is not "Dynamic" at all, there's no tactics in game because:
> The game will be more about working as an army, and not about who is better at being a rambo dancer.

I don't understand how zipping around a battlefield as a soldier firing off rounds at someone is Dynamic.  I don't see how not being able to communicate with your team because of that being the primary means of combat, makes the game more dynamic.

Surely if people could communicate more with each other, combat was slowed down slightly, and made to be just a smidgen more realistic, that would make the overall gameplay a hell of a lot more dynamic?

**Comment by Wesreidau** [comment]
I would absolutely keep the "run" speed tied to the oxyloss damage, as this simultaneously makes wounded  players slower and makes winded soldiers more vulnerable.

**Comment by TeknoKot** [comment]
Since we're on topic with the iron-sights, I think we should make it mandatory for people to use it, those who hipfire can gain heavy accuracy decrease(to stop PPSH's/MP40's/MG's prefiring blindly and running), unless they're 1-6 tiles close to each other, so assault classes can be a whole lot useful.

**Comment by Bernhaben** [comment]
To actually be effective at forcing Roleplay, promote cover, +accuracy while zoomed in gives people a real good defensive bonus. Advancing forces will have to find cover, rush to another piece of cover, and have others behind them or on their flank "Cover Fire", promoting communication. It would have to go like, "I'm advancing! COVER ME!" Strengthen limbs, give accuracy debuffs when aiming for limbs, and torso shots should be the norm.

**Comment by spacebear27** [comment]
Well if this whole WW2 thing doesn't work out, a musket-era server with line battles may be cool (in spirit with the movement and combat changes).

**Comment by Super3222** [comment]
If you're ever nerfing scopes again tie it with this idea. Just make walking in scope work, but trying to run and use your scope not work.

**Comment by MarinaGryphon** [comment]
The stamina thing sounds okay in theory, but as someone who's actually played on a server that uses it?

It's fucking _great_, man. 👍
