### ISSUE TITLE
Message Spamming

### ISSUE THREAD

**Issue by Alexshreds** [WW2-SS13/WW13#180]
When trying to join as a reinforcement wave-

Failed to spawn a new Russian squadron. 1 more draftees needed.
Failed to spawn a new Russian squadron. 1 more draftees needed.

Similar thing happens when an enemy is occupying the base except that message is repeated 3 times.

**Comment by kachnov** [comment]
how else is this supposed to be handled

**Comment by tylerh95** [comment]
Ideally, the message should only show once.

**Comment by Harcourt1** [comment]
This only happens at very low pop. Not a issue where it would effect anyone. Suggest closing issue.

**Comment by Muncher2112** [comment]
>how else is this supposed to be handled
