### ISSUE TITLE
Aiming at Hands

### ISSUE THREAD

**Issue by turnop** [WW2-SS13/WW13#190]
Aiming at someone's hands, upon a hit, takes them almost entirely out of the battle, as they are no longer able to use items in one of their hands. This makes absolutely no sense, as you are aiming at one of the smallest parts of the body. The meta should be to aim at the chest, as soldiers have been doing since forever, as it is the largest part of the body and contains the most vital organs. Aiming at extremities like hands and feet should have enormous maluses to hit.

**Comment by kachnov** [comment]
should be fixed in the next build
