### ISSUE TITLE
Tank Related Feedback

### ISSUE THREAD

**Issue by subdon** [WW2-SS13/WW13#198]
Regarding what i have seen so far in this match and think might be a issue with the actual tanks is:
## Too big sprites and object: 
first of all, the fact they are so big is directly proportional at the quality of the main sprite, decreasing its quality and making it look "ugly and poorly made", suggesting reducing it to 4x4
## EXTREMELY FAST turning around without a warning: 
its another issue, tanks are not supposed to be turning around this fast without a warning, tanks were made with the advantage of PROVIDING COVER, but how can a soldier trust the tank when it can TURN AROUND AND INSTANTLY GIB HIM without a warning, suggesting adding a "channeling EFFECT" or message to warn soldiers to MOVE THE FUCK OUT.
## Possible Counter Classes/Jobs:
If your tank is fucked the other tank will rape the entire team and unbalance battle, anti tank troopers were a thing in WW2, why not here?, normal soldier but with a rocket launcher.

**Comment by subdon** [comment]
I meant to write 2x2 as for sprites

**Comment by chesse20** [comment]
if they add a rocket launcher role people will just use it to get funny kills on infantary players

**Comment by The-clown-known-as-Pepe** [comment]
Then add limited ammo for rocket launcher?

**Comment by kachnov** [comment]
nerfed tanks and added anti tank troopers
