### ISSUE TITLE
squads should be indicated by slightly diffrent helmet colors

### ISSUE THREAD

**Issue by chesse20** [WW2-SS13/WW13#204]
very easy to forget what squad you are on so you should have a diffrent shade of black as german or a diffrent shade of green as russian based on what squad you are on

**Comment by subdon** [comment]
Good idea, would add to organization and proper strategic use of squads
 it is good to note that its not totally unrelated to history, in world war 2 helmets often used numbers or markings to identify platoon/company/squad and rank
https://en.wikipedia.org/wiki/Brodie_helmet#/media/File:M1917helmet.jpg

**Comment by coecoo** [comment]
The amount of different clothing items & helmets should be as distinctive as possible between the two factions, both by color and silhouette design.

**Comment by chesse20** [comment]
the black helmets of diffrent shades and green helmets of diffrent shades are fine for distinctivity. the s.s look too much like russians though and ive definitely shot one on accident because of it. thats for a diffrent suggestion thread of course
