### ISSUE TITLE
Inadequate tank/MG sprites, screams, jews for non-german factions, fix squads

### ISSUE THREAD

**Issue by Felkvir** [WW2-SS13/WW13#206]
All of these should be quick and painless so I'm not sure why they haven't been changed already. Scream sound files you could find a million anywhere that sound better than the current one, and more varieties. Tank sprites are literally the same for both sides at the moment, only distinguished by color and vague names. Even if you can't change them https://i.gyazo.com/75ca47fc80f8c4e4324f51786f0e7189.png to the first sprites you were messing with (t-34 and Pz III?), a normal person could make good looking tank sprites for both sides within the hour. Probably including more directions than the standard four if possible. German stationary MGs should also be easy. As for jews, they don't make sense to have amongst germans and they only cause shit anyways so change it to only be possible for partisans/civvies. 

I also want to say we desperately need a coherent squad system. If you look at CM as an example what they did is they didn't really change anything from a normal station servers security team except how many people are supervising squads and the fact that they could directly hand out orders visible for everyone in the squad. Now adding a radio operator/overwatch role clearly wouldn't be an issue, or making orders visible on the panel.

**Comment by tylerh95** [comment]
Issue is too broad. Scream sounds aren't a priority and is sort of a duplicate of #50. Tank sprites were purchased by a community member for use, I'm sure they'll be replaced however the original sprites aren't compatible with our tank system- which means we will have to adjust it. If you can make good looking tank sprites that are single piece in the next hour, I'll add them. Eight direction tank turret also planned. Stationary German MG needs a sprite. Squad fix is already in the pipeline.
