### ISSUE TITLE
S-mine catwalk sprite

### ISSUE THREAD

**Issue by JuicyReduxsDay** [WW2-SS13/WW13#216]

**Comment by JuicyReduxsDay** [comment]
There should be a texture/Sprite I died by a S-mine while on the bridge but I couldn't see the mine and this is also a problem for the Russian team as well I in a round I saw a Russian soldier walk on the bridge and before he could get to the invisible barrier his foot got blown off

**Comment by Muncher2112** [comment]
Can you clarify this issue?  I know there is a small sprite to indicate a planted mine.  Is the issue there is not a sprite for a mine on a specific turf?

**Comment by JuicyReduxsDay** [comment]
Sorry for the second issue Muncher It didn't update that I had posted a issue so I assumed I did something wrong anyways what I mean is that I can usually see the sprite. But what I mean is with some further testing that I can see the mine that I planted to test this but it blends in so well you might as well not be there its so faint but it might be my screen which i would find very unlikely

**Comment by JuicyReduxsDay** [comment]
Sorry about this issue with some contrast and brightness setting adjusted i can clearly see them now
