### ISSUE TITLE
Ladder Camping with a tank

### ISSUE THREAD

**Issue by JuicyReduxsDay** [WW2-SS13/WW13#218]
I went up a ladder and got instantly  gibed by a German panzer. I'd suggest making the ladder rooms impenetrable by German panzers/artillery. Or make a look up and down ladder feature so you know your not going to get fucked by something like that or even a s mine

**Comment by GelatinousGlob** [comment]
I think this could be partially solved with tank barricades that either damaged the tank heavily to knock through or were just not penetrable by the tank. Tank mines would help too. Especially considering how tanks make pretty much all sandbags and fortifications pointless when they should only be destructible by explosives.

**Comment by kachnov** [comment]
no longer an issue; there's now a look up/down ladder feature
