### ISSUE TITLE
Backup/Renewable Supplies

### ISSUE THREAD

**Issue by coecoo** [WW2-SS13/WW13#221]
There is a dire need for both sides to get in new supplies. In particular, doctors need advanced trauma kits, extra surgical tools and even blood while soldiers will all require ammo if a match carries on past a certain point.

**Comment by Muncher2112** [comment]
Also a way to give the conductor more to do.

**Comment by JuicyReduxsDay** [comment]
some rounds i find it is a problem but most it isnt i think losing supplies really comes from people taking more than they need and dying without using any of it like some people take three grenades some take five or more rifle clips ive seen it happen maybe they could emplement it that if a round goes on for say 1 hour and 50 minutes supplies come in from the qms underground tunnel and for the germans it comes from the airport in a ju57

**Comment by Bernhaben** [comment]
The QM's underground tunnel is a placeholder for the Cargo Truck we are implementing. The Germans are still far off.

**Comment by Wesreidau** [comment]
Both armories have space provisioned for a truck that will operate like a normal supply shuttle providing arms and munitions for supply points using a typewriter-themed interface.
