### ISSUE TITLE
[Suggestion] Partisans having a PTRD

### ISSUE THREAD

**Issue by NobodyNotable** [WW2-SS13/WW13#234]
Partisans very often get annihilated by the tanks of either side as soon as that side decides to attack them. Partisans on the other hand have little to no ways of fighting said tanks.
Partisans should, perhaps have a PTRD spawn in their factory(like it did before the tank update) but, perhaps, with limited ammo (Probably enough to take down a tank but not enough to go and meme soviet tanks right away, so probably around 4?) so they would be able to at least put up some sort of a fight.

**Comment by coecoo** [comment]
Doesn't fit realistically for them to have it and soviets are currently getting fucked on a daily basis 60 seconds in the game due to paratroopers as it is.

**Comment by NobodyNotable** [comment]
You could just explain it as them stealing one/having a stolen one.  Aside, as I said, it should not be enough to go on a tank destroying spree. It should just be enough to fight back if someone happens to attack  them with one.

**Comment by spacepurp** [comment]
-1 
terrible idea, stop being retarded

**Comment by calzilla1** [comment]
I say have a random arsenal each time
