### ISSUE TITLE
Different Bayonet Sprites/ A new gun

### ISSUE THREAD

**Issue by verynisepersin** [WW2-SS13/WW13#270]
I think that for Russia, in the armory there should be spike bayonets, and the Guards should spawn with a special blade bayonet that attaches to their Svt-40, just like in real life. There should also be a German role that gets either a Gewehr 41 that is loaded by two stripper clips, or a Gewehr 43, magazine loaded akin to the SVT. Players with the Gewehr should be able to use the standard German blade bayonets.
  Another neat feature would be to allow the SVT to be loaded by stripper clip when the magazine is inserted and empty.

**Comment by Eddyskingdom** [comment]
we have them now
