### ISSUE TITLE
Stop swallowing your teeth

### ISSUE THREAD

**Issue by tylerh95** [WW2-SS13/WW13#35]
Teeth that are knocked out disappear.

**Comment by tylerh95** [comment]
Tested, the teeth do fall out and spawn as expected, however they need a sprite.

**Comment by mattroks101** [comment]
They had a sprite in Interstation-Two but I'm guessing it was removed.

**Comment by Shephoris** [comment]
**ON IT!**

**Comment by Shephoris** [comment]
**DONE!**
