### ISSUE TITLE
bunker map for eddyskingdom

### ISSUE THREAD

**Issue by awesine** [WW2-SS13/WW13#353]
● ╰╯● - Today at 7:40 AM
ok hear me out
epic gamer idea:
a tight, claustrophobic bunker raid map
(SPLD-Ally) Eddyskingdom - Today at 7:40 AM
close combat
● ╰╯● - Today at 7:40 AM
yes\
tight hallways
i was thinking
soviets start aboveground
and raid a german bunker
which the germans defend and counter attack
(SPLD-Ally) Eddyskingdom - Today at 7:41 AM
that can work
● ╰╯● - Today at 7:41 AM
with the focus on SMGs instead of rifles
sandbag machine gun covered hallways
(SPLD-Ally) Eddyskingdom - Today at 7:41 AM
i can make a forst like map with a german bunker(edited)
● ╰╯● - Today at 7:41 AM
grenades would become actually useful
if i knew how ladders worked i could make one
(SPLD-Ally) Eddyskingdom - Today at 7:42 AM
i know
so i can make it
● ╰╯● - Today at 7:42 AM
like how to make one ladder connect to another z-level
(SPLD-Ally) Eddyskingdom - Today at 7:42 AM
put it in Github
in issues

**Comment by Eddyskingdom** [comment]
i will work on it after i'm done with the City, forest, piller map updates and i probely be done in  2 weeks or so with that map if i get time to do it

**Comment by cariosecus** [comment]
Implemented
