### ISSUE TITLE
Surgery

### ISSUE THREAD

**Issue by tylerh95** [WW2-SS13/WW13#4]
Surgery sometimes doesn't work apparently. Needs testing to see exactly what is broken.

**Comment by Shephoris** [comment]
Surgery is not broken, I have tested surgery extensively.  It's most likely due to people not knowing the surgery mechanics.  Suggest we set up an official wiki to fix this issue.

**Comment by Soundwavesghost** [comment]
Indeed, the brute damage rebreaking bones isn't easy to remember for the new doctorss.

**Comment by tylerh95** [comment]
Surgery works, people just didn't know how to use it. Needs wiki page
