### ISSUE TITLE
Add Vehicles

### ISSUE THREAD

**Issue by tylerh95** [WW2-SS13/WW13#43]
Bikes
Cars
Tanks
Planes
Half-tracks

**Comment by Chuckachu** [comment]
Little something I tinkered with this morning.


![tank test](https://user-images.githubusercontent.com/5963543/27994013-b0c675c0-6482-11e7-82f9-523e04a32664.png)




Original creator: https://opengameart.org/content/tanks-top-down-ww2

**Comment by subdon** [comment]
I have a better idea on how to handle the vehicles
Mechs:
Grab a mech, equip it with lethals and perhaps a missile launcher
Reskin it with tank sprites
Assign a job named "Operator/Driver" to pilot it
