### ISSUE TITLE
Binocular zoom abuse

### ISSUE THREAD

**Issue by ext9z3** [WW2-SS13/WW13#444]
Speaking shortly, you can use binocular and shoot from basic bolt-rifle with no attachments with greatest zoom. Zoom needed to by strongly fixed by the active hand with a binocular

**Comment by Eddyskingdom** [comment]
easy fix we will work on it

**Comment by Eddyskingdom** [comment]
send a screens shot of it happening

**Comment by ext9z3** [comment]
what confirmation just do same shit in the discription

**Comment by Eddyskingdom** [comment]
#569 it is fix
