### ISSUE TITLE
Unspent Cartridge Sprite

### ISSUE THREAD

**Issue by tylerh95** [WW2-SS13/WW13#48]
Add a new sprite for unspent bullets so that they can be distinguished from empty shell casings without having to examine them.

**Comment by Bernhaben** [comment]
This can actually be easily done. Just give the old bullet sprite a bit of a black-ish detail on one of the ends.

**Comment by Shephoris** [comment]
**ON IT**

**Comment by Eddyskingdom** [comment]
seems like its never done i can probely do?

**Comment by Eddyskingdom** [comment]
it's done i made the cartiges
