### ISSUE TITLE
Taislin needs to learn how to code. 

### ISSUE THREAD

**Issue by Harcourt1** [WW2-SS13/WW13#483]
I'm away from my computer but fix your PR, that will runtime because there is no item. Replace the removed code with an item like in the previous options.

**Comment by Harcourt1** [comment]
Do it asap then !s updateserver

**Comment by Harcourt1** [comment]
I would be surprised if your code even compiled. So maybe it's down rn.

**Comment by Harcourt1** [comment]
Comment back and let me know

**Comment by Harcourt1** [comment]
Somebody yell at him.

**Comment by Harcourt1** [comment]
@taislin

**Comment by ShinHKPDes** [comment]
lmao!!
