### ISSUE TITLE
Sugestion: first in first out renforcment queues with no cap

### ISSUE THREAD

**Issue by Supermichael777** [WW2-SS13/WW13#55]
![image](https://user-images.githubusercontent.com/11540177/27990303-4532d856-6420-11e7-8b20-343a32bd7c99.png)

This is no fun.

so:
You are now x in the Russian reinforcement queue. Next wave will serve 1-y. Current German queue is z.

if reinforcements are suspended you should also say that in the message
and delay the ability to join the queue for a few minutes after death

**Comment by Shephoris** [comment]
You can click the lobby tab to see how many reinforcements slots are taken for a given team, and if the side is locked. It also gives you a countdown until those reinforcements will be deployed.  That message is sent when one team has had more reinforcements than the other. The side is locked to ensure balance.
