### ISSUE TITLE
Battlefield Map and Anemometer

### ISSUE THREAD

**Issue by tylerh95** [WW2-SS13/WW13#66]
This would be a functional and design improvement to the artillery coordinate checking / scouting system.

The scout would have a battlefield map, which would tell them their coordinates when used.

However in addition to the coordinates, the scout must find the proper offset to have the artillery sent to by measuring the wind speed using the anemometer. To make the system even better, the wind speed / direction should randomly change every so often requiring further scouting.

**Comment by Wesreidau** [comment]
I think the addition of wind blowing shells a fixed offset from the targeted coordinate would be very useful, making either the gunner or the scout have to correct their aim. I wouldn't go so far as adding a device to measure the wind, however. Lets make people eyeball the tile offset and do some math in their heads.
