### ISSUE TITLE
STG doesn't fit in backpack

### ISSUE THREAD

**Issue by Difrit** [WW2-SS13/WW13#74]
As title. You can fit four rifles or any other sort of weapon in there, but apparently the STG is too big.

**Comment by TeknoKot** [comment]
In particularly I'd be a fan of removing the way of fitting rifles in backpack and adding another backpack slot above the other one.

**Comment by DoctorHonkington** [comment]
It'd be nice to have a slot specifically for rifles considering they'd probably have a sling that could allow the rifle to hang round the shoulder. Pretty much what TeknoKot said.

**Comment by Bernhaben** [comment]
Similar to how lifeweb has two backpack slots.
