### ISSUE TITLE
SSD and put in bed should reopen slots and be ignored by the battle rattle updates.

### ISSUE THREAD

**Issue by Soundwavesghost** [WW2-SS13/WW13#80]
Folks that SSD and then strapped to a bed should not count for their sides numbers. In the near/far future they should also be a mechanic to remove them altogether so others can fill their rolls.

**Comment by Bernhaben** [comment]
People can abuse this as a bug. They can make one more special troop such as an SS Soldier by meta-ing to go SSD and then go back in-game. What I have in mind is an SSD Train, one where, if you hop on it, you will instead go back to "Germany" to "recuperate" freeing up your slot if you're one of the elites.

**Comment by Soundwavesghost** [comment]
Hmmm. I am trying to find sprites to work as a supply truck for the QMs....could be a good way to get ride of them as well I suppose.

**Comment by Bernhaben** [comment]
Hrm, Opel Blitz trucks were the most common transport truck used by the German Army. Here's a link

https://thumbs.dreamstime.com/z/opel-blitz-supply-truck-westernhanger-uk-july-ex-ww-german-army-heads-toward-arena-battle-re-enactment-display-58104471.jpg

There are Krupp Protzes, Henschels, andd..... Schwerers.  But yeah... Opel Blitz.

**Comment by Soundwavesghost** [comment]
Just realized that this would likely need to be handled on top of the existing  "Shuttle" stuff which would be only top down. I'll have to dig out those sprites and see if they can be visually flipped about. Front end of the truck from top down, bed of the truck being the trail railings and the back being open. Perhaps the whole bed would be 3 wide by 4 long?

**Comment by Bernhaben** [comment]
Yeah, a single truck would be nice. That could call in additional ammo/supplies  as well as bring troops back home. A Convoy wouldn't be a bad idea either.

**Comment by Soundwavesghost** [comment]
Go ahead and close this one. I'll reopen when I have something better to contribute.
