### ISSUE TITLE
Rank Issues

### ISSUE THREAD

**Issue by Difrit** [WW2-SS13/WW13#81]
Feldwebel is a sergeant-equivalent. Gruppenfuhrers are a regiment-level command position. Feldwebel is the overall field commander for some odd reason in NML. Fix please.

**Comment by Wesreidau** [comment]
The German ranks are definitely wrong on several points. The platoon "zug" should be lead by a Leutnant who is the Zugfuhrer. Gruppenfuhrers are still accurate. A platoon sergeant belongs in here somewhere as an Unterofficier. But are we making slots that are roles, or ranks?
